### ISSUE TITLE
[BUG]: No Entries Displayed in "Muxe" Tab After Adding IPTV Network

### ISSUE THREAD

**Issue by sickboy2711** [tvheadend/tvheadend#1650] opened 2024-02-19 22:53 UTC
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2253~g2ca8a19e4

### Platform

Raspberry Pi OS (Bullseye)

### Architecture

ARMv7 (arm)

### Category

Muxes

### Description

I compiled the latest TVHeadend 4.3-2253~g2ca8a19e4 on my Raspberry Pi. After installation, I added an IPTV network via the wizard. It shows a total of 225 Muxes and all services. However, there are no entries displayed in the "Muxes" tab.

### Reproduction

1. Start the Wizzard
2. Select IPTV Automatic Network
3. paste m3u URL
![Networks](https://github.com/tvheadend/tvheadend/assets/30045112/209fc4ea-73ff-4749-ada0-f56ccc88b349)
![Muxes](https://github.com/tvheadend/tvheadend/assets/30045112/27aafbf1-8af9-4a5b-8233-90f4e458fa3e)
![services](https://github.com/tvheadend/tvheadend/assets/30045112/432ad82a-c6c1-4c0c-970a-29eab4ce5d6c)

**Comment by Flole998** [comment] 2024-02-19 22:55
This issue report is missing debug logs.

**Comment by DeltaMikeCharlie** [comment] 2024-02-19 23:03
Is the M3U correctly formatted?

**Comment by sickboy2711** [comment] 2024-02-19 23:06
@Flole998 where did i found the debug report?
@DeltaMikeCharlie: i got the m3u from my telerising api http://xxx.xxx.x.xxx:5000/api/sky/file/channels.m3u?ffmpeg=true IMO it should be correct

**Comment by lordduckstein** [comment] 2024-02-20 14:30
I can confirm the issue, after the last update. I have no muxes and services displayed

**Comment by sickboy2711** [comment] 2024-02-20 18:24
@Flole998 If the setup assistant starts immediately after installation, the debug log is not yet activated. If you can tell us how to access it from the background, I will gladly provide it

**Comment by Flole998** [comment] 2024-02-20 18:26
You can enable the debug logs by starting Tvheadend with the appropriate parameters. Check the documentation for additional details on what parameters to use. Likely the `--trace` parameter with the iptv subsystem is a good start.

**Comment by sickboy2711** [comment] 2024-02-20 18:33
TVH starts automatic
`[Unit]
Description=tvheadend
After=telerising.service

[Service]
Type=forking
PIDFile=/run/tvheadend.pid
ExecStart=/usr/local/bin/tvheadend -f -p /run/tvheadend.pid -C -u hts -g video
ExecStop=/usr/bin/rm /run/tvheadend.pid
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target`

I've actually explained the whole procedure; lordduckstein has the same issue. So, there must be something wrong with the software. Just a reminder, I'm a user, not a developer. If reporting bugs isn't desired, please state so in Git

**Comment by Flole998** [comment] 2024-02-20 18:44
> If reporting bugs isn't desired, please state so in Git

Bug reports are desired here, support requests should go in the forum. A bug report has debug logs and information on how to reproduce the issue. This report is missing the debug logs, so they should be added.

**Comment by Flole998** [comment] 2024-02-20 19:21
I followed your steps on a clean install from cloudsmith on the latest Ubuntu server OS and could not reproduce it.

**Comment by Flole998** [comment] 2024-02-20 19:45
Again, can't reproduce. Provide debug logs and check if the API at `/api/mpegts/mux/grid` is providing a list of muxes or I am going to close this. Also if you are not using the official docker container but some modified one instead you should contact the maintainer of it for support.

**Comment by lordduckstein** [comment] 2024-02-20 21:12
Your are right when I go to standard image there a no problems.I use the icam support thealhu/tvheadend:latest ther is the bug since 24 hours. Sorry for the false alarm

**Comment by chewitt** [comment] 2024-02-21 01:14
Closing as not our bug. Thanks for the update.

**Closed by chewitt** 2024-02-21 01:14 UTC
Labels: needs-more-info
