### ISSUE TITLE
[BUG]: compiling with Autobuild.sh failed due dpkg-buildpackage version error

### ISSUE THREAD

**Issue by Smyl3** [tvheadend/tvheadend#1683] opened 2024-04-08 02:07 UTC
### Tvheadend Version

v4.3 (development)

### Build Number

none

### Platform

Debian 12 (Bookworm)

### Architecture

ARMv7 (arm)

### Category

Packaging

### Description

cloned actual tvheadend repo, after configure with same parameters and run Autobuild.sh , it generates a dpkg-buildpackage error under Windows WSL2 and in chrooted raspberry os 32bit either  with Debian bookworm OS:

```
➜  tvheadend git:(master) AUTOBUILD_CONFIGURE_EXTRA=--disable-ffmpeg_static\ --disable-libfdkaac_static\ --disable-libtheora_static\ --disable-libopus_static\ --disable-libvorbis_static\ --disable-libvpx_static\ --disable-libx264_static\ --disable-libx265_static\ --disable-libfdkaac\ --disable-libopus\ --disable-libvorbis\ --disable-libvpx\ --disable-libx264\ --disable-libx265\ --disable-avahi\ --disable-dbus_1\ --disable-bintray_cache\ --disable-execinfo\ --disable-hdhomerun_static\ --disable-hdhomerun_client\ --disable-libav\ --enable-pngquant\ --enable-trace\ --disable-vaapi ./Autobuild.sh
OS identified using os-release file
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Building for bookworm-x86_64
dpkg-buildpackage: warning:     debian/changelog(l1): version '~bookworm' is invalid: version number does not start with digit
LINE: tvheadend (~bookworm) bookworm; urgency=low
dpkg-buildpackage: info: source package tvheadend
dpkg-buildpackage: info: source version unknown
dpkg-buildpackage: error: version number does not start with digit
```

```
root@DESKTOP:/home/pi/tvheadend# AUTOBUILD_CONFIGURE_EXTRA=--disable-ffmpeg_static\ --disable-libfdkaac_static\ --disable-libtheora_static\ --disable-libopus_static\ --disable-libvorbis_static\ --disable-libvpx_static\ --disable-libx264_static\ --disable-libx265_static\ --disable-libfdkaac\ --disable-libopus\ --disable-libvorbis\ --disable-libvpx\ --disable-libx264\ --disable-libx265\ --disable-avahi\ --disable-dbus_1\ --disable-bintray_cache\ --disable-execinfo\ --disable-hdhomerun_static\ --disable-hdhomerun_client\ --disable-libav\ --enable-pngquant\ --enable-trace\ --disable-vaapi ./Autobuild.sh
OS identified using lsb_release command
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Building for bookworm-armv7l
dpkg-buildpackage: warning:     debian/changelog(l1): version '~bookworm' is invalid: version number does not start with digit
LINE: tvheadend (~bookworm) bookworm; urgency=low
dpkg-buildpackage: info: source package tvheadend
dpkg-buildpackage: info: source version unknown
dpkg-buildpackage: error: version number does not start with digit
```
debian/changelog:
```
tvheadend (~bookworm) bookworm; urgency=low

  * ab6ea89 Update manpage

  * The full changelog(s) can be found at
    https://tvheadend.org/projects/tvheadend/wiki/Releases
    https://github.com/tvheadend/tvheadend

 -- Andreas Öman <andreas@tvheadend.org>  Sun, 07 Apr 2024 22:14:47 +0100
```
debian/control:
```
root@DESKTOP:/home/pi/tvheadend# cat debian/control
Source: tvheadend
Section: video
Priority: extra
Maintainer: Tvheadend Project <admin@tvheadend.org>
Build-Depends: debhelper (>= 7.0.50), pkg-config, gettext, libavahi-client-dev, libssl-dev | libssl1.0-dev, zlib1g-dev, wget, bzip2, git-core, liburiparser-dev, python | python3, python-requests | python3-requests, ca-certificates, cmake, libpcre2-dev | libpcre3-dev, libdvbcsa-dev
Standards-Version: 3.7.3

Package: tvheadend
Architecture: any
Depends: ${shlibs:Depends}, libavahi-client3, zlib1g, liburiparser1, bzip2
Recommends: xmltv-util, python, python-requests
Enhances: showtime
Replaces: hts-tvheadend
Homepage: https://tvheadend.org
Description: Tvheadend
 Tvheadend is a TV streaming server and digital video recorder.
   - supports a variety of inputs (DVB-S(2)/T(2)/C, ISDB-S/T/C, ATSC-T/C, IPTV, SAT>IP, HDHR)
   - supports a variety of clients (Movian, Smart TV, Kodi, VLC)

Package: tvheadend-dbg
Architecture: any
Section: debug
Priority: extra
Depends: tvheadend (= ${binary:Version}), ${misc:Depends}
Description: Debug symbols for Tvheadend
 This package contains the debugging symbols for Tvheadend.
```

### Reproduction

1. git clone --depth 1 https://github.com/tvheadend/tvheadend.git
2. install missing dependencies: gettext libssl-dev libpcre2-dev zlib1g-dev liburiparser-dev libavahi-client-dev cmake libiconv-hook-dev libdvbcsa-dev
3. AUTOBUILD_CONFIGURE_EXTRA=--disable-ffmpeg_static\ --disable-libfdkaac_static\ --disable-libtheora_static\ --disable-libopus_static\ --disable-libvorbis_static\ --disable-libvpx_static\ --disable-libx264_static\ --disable-libx265_static\ --disable-libfdkaac\ --disable-libopus\ --disable-libvorbis\ --disable-libvpx\ --disable-libx264\ --disable-libx265\ --disable-avahi\ --disable-dbus_1\ --disable-bintray_cache\ --disable-execinfo\ --disable-hdhomerun_static\ --disable-hdhomerun_client\ --disable-libav\ --enable-pngquant\ --enable-trace\ --disable-vaapi ./configure 
4. AUTOBUILD_CONFIGURE_EXTRA=--disable-ffmpeg_static\ --disable-libfdkaac_static\ --disable-libtheora_static\ --disable-libopus_static\ --disable-libvorbis_static\ --disable-libvpx_static\ --disable-libx264_static\ --disable-libx265_static\ --disable-libfdkaac\ --disable-libopus\ --disable-libvorbis\ --disable-libvpx\ --disable-libx264\ --disable-libx265\ --disable-avahi\ --disable-dbus_1\ --disable-bintray_cache\ --disable-execinfo\ --disable-hdhomerun_static\ --disable-hdhomerun_client\ --disable-libav\ --enable-pngquant\ --enable-trace\ --disable-vaapi ./Autobuild.sh

**Comment by Flole998** [comment] 2024-04-08 06:08
Casting with depth 1 does not allow the version number to be determined. WSL is not supported. In a proper environment there is no issue, see GitHub actions. If you want to improve Tvheadend so it detects this corner case we can track it as a new feature/enhancement, otherwise I'll close this.

**Comment by Smyl3** [comment] 2024-04-08 07:36
I think cross compiling under WSL and git cloning with depth 1 option are common use cases, so a check for this situation and an error message would be great at least to avoid taking lot of time with investigation without any clue why it doesn't work as I did. Thanks.

**Comment by Saentist** [comment] 2024-04-08 12:29
@Smyl3 
`--depth 1` dont work, because way release number is computed.
WSL work without problem for building packages.

**Comment by CvH** [comment] 2024-04-08 13:40
The version generation works by counting the git commits and at base of the tags+branch.
https://github.com/tvheadend/tvheadend/blob/master/support/version#L9

So it works like intended but does not work if you just get the tarball or zip.
We just sed the version, works since decades :)
`sed -e 's/VER="0.0.0~unknown"/VER="1.2.3.4"/g' -i support/version`

**Comment by Flole998** [comment] 2024-04-08 14:29
> an error message would be great at least to avoid taking lot of time with investigation without any clue why it doesn't work as I did.

I am not sure why WSL doesn't catch this, on other systems it results in an "unknown". Feel free to have a look at what `support/version` reports.

**Comment by CvH** [comment] 2024-04-08 15:14
> I am not sure why WSL doesn't catch this

The problem is not WSL, the problem is that the script can't handle the depth=1.
Because its still a valid git repository and that corner case is not handled.

same at Debian/Buntu

```
git clone --depth=1 https://github.com/tvheadend/tvheadend.git
cd tvheadend/
./support/version
```

```
root@debian12:~/tvheadend# ./support/version 

root@debian12:~/tvheadend# 
```

**Comment by Smyl3** [comment] 2024-04-08 19:11
> ./support/version

Thanks all of the reply.
I can confirm what @CvH wrote.
Under WSL Debian and chrooted Raspberry OS, the command gave back empty string.
After switching to full git clone with _git fetch --unshallow_ I got right version with the command.
Cloned directory size was changed 136M -> 182M of data.

**Comment by Flole998** [comment] 2024-04-08 19:16
This is indeed a bug, it broke a few weeks ago. I will fix this right now.

**Closed** 2024-04-08 22:49 UTC
Labels: needs-more-info

**Comment by xswqaz** [comment] 2025-05-17 05:25
Here is debug log related with AC3

```
May 17 14:24:12 tvheadend[243463]: <none>: esfilter: "ATSC/303MHz/(HD) YTN" 002 05732 AC3 
May 17 14:24:12 tvheadend[243463]: transcode: 0007: 02:AC3: ==> Filtered out
May 17 14:24:12 tvheadend[243463]: tbl-base: pmt:    type AC3 position 0
May 17 14:24:12 tvheadend[243463]: pcr: ATSC/303MHz/(HD) YTN: audio DTS: -9223372036854775808 dts 6638703772 [AC3/5732]
May 17 14:24:12 tvheadend[243463]: parser: deliver (pkt stream 2 AC3 pcr <unset> dts <unset> pts <unset> dur 0 len 0 err 1)
May 17 14:24:12 tvheadend[243463]: pcr: ATSC/303MHz/(HD) YTN: audio DTS: 6638711257 dts 6638721052 [AC3/5732]
May 17 14:24:12 tvheadend[243463]: parser: deliver (pkt stream 2 AC3 pcr 6638711257 dts 6638703772 pts 6638703772 dur 2880 len 1024 err 0)
May 17 14:24:12 tvheadend[243463]: parser: deliver (pkt stream 2 AC3 pcr 6638711257 dts 6638706652 pts 6638706652 dur 2880 len 1024 err 0)
```
