### ISSUE TITLE
[BUG]: channel categorization

### ISSUE THREAD

**Issue by clear-sky** [tvheadend/tvheadend#1790] opened 2024-12-15 15:01 UTC
### Tvheadend Version

v4.3 (development)

### Build Number

4.3-2354~gadef81b8d

### Platform

Other..

### Architecture

Intel x86_64

### Category

API

### Description

I think the program is not working properly in channel categorization. Let me explain better.
I tried two Russian satellites, one in orbit at 52 degrees East and the other at 80 degrees East.
After searching the channels, some strange results were obtained! Look at the picture I sent.
As you can see, there are channels with the same name in two different directions, but the program groups them both into one catalog.
Logically, these two channels should be separate so they can be managed - what is your opinion?

![tv](https://github.com/user-attachments/assets/e97b9dc7-f895-430a-a38d-4403f102bea3)

**Comment by Flole998** [comment] 2024-12-15 15:07
Not a bug, you selected "merge same name" when mapping them so they got merged.

**Closed by Flole998** 2024-12-15 15:07 UTC

**Comment by chewitt** [comment] 2024-12-15 15:09
The only satellite services that legally carry BBC UK channels aren't available on Russian satellites. Pirate IPTV feed issues aren't our problem either.

**Comment by clear-sky** [comment] 2024-12-15 15:29
many many thanks for reply
